#!/usr/bin/env python3
"""
Convert notes-to-blog HTML exports into Jekyll _posts/*.md files.

Assumptions:
- notes-to-blog export folder: ~/Desktop/notes-to-blog-output
- Jekyll site repo:            ~/Desktop/verycooluser.github.io
- Jekyll posts folder:         ~/Desktop/verycooluser.github.io/_posts

Usage (from the repo root):
    python3 script/notes_to_posts.py
"""

import re
from pathlib import Path
from datetime import datetime, date

# --- CONFIG: adjust if your paths change later ------------------------------

NOTES_EXPORT_ROOT = Path("~/Desktop/notes-to-blog-output").expanduser()
JEKYLL_ROOT = Path("~/Desktop/verycooluser.github.io").expanduser()
POSTS_DIR = JEKYLL_ROOT / "_posts"


# --- Helpers ----------------------------------------------------------------

def slugify(title: str) -> str:
    """Turn a note title into a Jekyll-friendly slug."""
    title = title.strip().lower()
    # Replace non-alphanumeric with hyphens
    title = re.sub(r"[^a-z0-9]+", "-", title)
    # Remove leading/trailing hyphens
    title = title.strip("-")
    return title or "untitled"


def extract_title_and_body(html: str, default_title: str) -> tuple[str, str]:
    """Extract <h1> as title and <body> content as body HTML."""
    # Try to get title from first <h1>...</h1>
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.IGNORECASE | re.DOTALL)
    if m:
        raw_title = m.group(1)
        # Strip HTML tags inside the h1
        title_text = re.sub(r"<[^>]+>", "", raw_title).strip()
    else:
        title_text = default_title

    # Extract <body>...</body>
    m = re.search(r"<body[^>]*>(.*)</body>", html, re.IGNORECASE | re.DOTALL)
    if m:
        body_html = m.group(1).strip()
    else:
        # Fall back to whole document (not ideal, but safe)
        body_html = html.strip()

    return title_text, body_html


def find_existing_post_for_slug(slug: str):
    """Return an existing _posts file that ends with -slug.md, if any."""
    pattern = f"*-{slug}.md"
    matches = list(POSTS_DIR.glob(pattern))
    return matches[0] if matches else None


def date_from_filename(name: str):
    """Parse YYYY-MM-DD from the start of a _posts filename."""
    try:
        prefix = name.split("-", 3)  # YYYY, MM, DD, rest
        y, m, d = int(prefix[0]), int(prefix[1]), int(prefix[2])
        return date(y, m, d)
    except Exception:
        return None


def file_mtime_date(path: Path) -> date:
    """Use the file's modification time as a date."""
    ts = path.stat().st_mtime
    return datetime.fromtimestamp(ts).date()


def build_front_matter(title: str) -> str:
    """Return YAML front matter for a Jekyll post."""
    safe_title = title.replace('"', '\\"')
    fm_lines = [
        "---",
        'layout: post',
        f'title: "{safe_title}"',
        "---",
        "",
    ]
    return "\n".join(fm_lines)

def strip_notes_to_blog_metadata(body_html: str) -> str:
    """Remove boilerplate from notes-to-blog exports:
    - Published-date div
    - Back to site button/link
    - The boilerplate <h1> title generated by notes-to-blog
    """

    # 1. Remove the published-date block
    body_html = re.sub(
        r'<div\s+class="published-date">.*?</div>',
        "",
        body_html,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # 2. Remove "Back to site" button or link
    # Covers <a class="back" ...>Back to site</a> and variations
    body_html = re.sub(
        r'<a[^>]*>\s*Back to site\s*</a>',
        "",
        body_html,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # 3. Remove the boilerplate <h1> title (the first one in the document)
    # We do NOT want to remove real <h2>/<h3>/<h4> headings inside your notes.
    body_html = re.sub(
        r"<h1[^>]*>.*?</h1>",
        "",
        body_html,
        count=1,                      # important: only remove the *first* <h1>
        flags=re.IGNORECASE | re.DOTALL,
    )

    return body_html.strip()

# --- Main conversion --------------------------------------------------------

def convert_all_notes() -> None:
    if not NOTES_EXPORT_ROOT.exists():
        raise SystemExit(f"Notes export folder not found: {NOTES_EXPORT_ROOT}")

    if not POSTS_DIR.exists():
        raise SystemExit(f"Jekyll _posts folder not found: {POSTS_DIR}")

    print(f"Using notes export root: {NOTES_EXPORT_ROOT}")
    print(f"Writing Jekyll posts into: {POSTS_DIR}")
    print("Scanning for HTML files...")

    html_files = sorted(NOTES_EXPORT_ROOT.rglob("*.html"))
    if not html_files:
        print("No .html files found under export root.")
        return

    converted = 0

    for html_path in html_files:
        # Skip listing pages:
        if html_path.name.lower() == "index.html":
            continue

        print(f"- Processing {html_path.relative_to(NOTES_EXPORT_ROOT)}")

        html = html_path.read_text(encoding="utf-8", errors="ignore")
        default_title = html_path.stem
        title, body_html = extract_title_and_body(html, default_title)
        body_html = strip_notes_to_blog_metadata(body_html)
        slug = slugify(title)

        # See if we already have a post for this slug
        existing = find_existing_post_for_slug(slug)
        if existing:
            # Reuse its date from filename if possible
            existing_date = date_from_filename(existing.name) or file_mtime_date(existing)
            post_path = existing
        else:
            # New post: choose a date based on the note's mtime
            d = file_mtime_date(html_path)
            post_filename = f"{d:%Y-%m-%d}-{slug}.md"
            post_path = POSTS_DIR / post_filename

        front_matter = build_front_matter(title)
        content = front_matter + body_html + "\n"

        post_path.write_text(content, encoding="utf-8")
        converted += 1

    print(f"Done. Converted / updated {converted} posts.")


if __name__ == "__main__":
    convert_all_notes()

